//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam2
    {
        public int ExamID { get; set; }
        public string Subject { get; set; }
        public string Grade { get; set; }
        public string TeacherName { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
    }
}
