//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Porject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int rowNum { get; set; }
        public Nullable<int> Amount_teacher_ { get; set; }
        public Nullable<int> Amount_student { get; set; }
        public Nullable<int> Amount_office { get; set; }
        public Nullable<int> Amount_cleaner_ { get; set; }
        public Nullable<int> Amount_bill { get; set; }
    }
}
