//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFee
    {
        public int SalaryId { get; set; }
        public int StudentID { get; set; }
        public string Name { get; set; }
        public string Subject { get; set; }
        public int Amount { get; set; }
        public string Month { get; set; }
        public string Date_Time { get; set; }
    
        public virtual StudentTB StudentTB { get; set; }
    }
}
